name: Bump Version and Create Release

on:
  pull_request:
    types: [closed]
    branches: [master, main]

permissions:
  contents: write

jobs:
  bump_version_and_create_release:
    name: Bump version and create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Calculate bumped version
        id: test_tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true

      - name: Run version bump script
        run: |
          python3 Scripts/increment_version.py ${{ steps.test_tag_version.outputs.new_tag }}

      - name: Set up Git and Push changes
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: bump the Flakkari version to ${{ steps.test_tag_version.outputs.new_tag }}" || true
          git push || true

      - name: Create Tag
        id: tag_version
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ steps.test_tag_version.outputs.new_tag }}
          git push origin ${{ steps.test_tag_version.outputs.new_tag }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ steps.test_tag_version.outputs.new_tag }}
          name: Flakkari ${{ steps.test_tag_version.outputs.new_tag }}
          body: ${{ steps.test_tag_version.outputs.changelog }}
          generateReleaseNotes: true
